'''*H
Copyright 2017 Transport Systems Catapult (The Catapult)
All rights reserved
For use only for the purpose agreed with The Catapult
#H'''

import os, subprocess, datetime

folder = os.path.dirname(os.path.realpath(__file__))
old_cwd = os.getcwd()
os.chdir(folder)
headerFilename = os.path.join(folder, "git_info.h")

desc = subprocess.check_output(["git", "describe"]).strip()
branch = subprocess.check_output(["git", "rev-parse", "--abbrev-ref", "HEAD"]).strip()
diff = subprocess.check_output(["git", "diff", "--name-only"]).strip()
uncommittedChanges = bool(diff)

descParts = desc.split('-')
if len(descParts) == 1:
    versionString = descParts[0]
    additionalCommits = 0
    objectName = ""
elif len(descParts) == 3:
    versionString = descParts[0]
    objectName = descParts[2]
    try:
        additionalCommits = int(descParts[1])
    except ValueError:
        additionalCommits = 0
        versionString = "v-1.5"

else:
    versionString = "v-1.1"
    additionalCommits = 0
    objectName = "INVALID:0"

if versionString[0] == 'v':
    versionParts = versionString[1:].split('.')
    if len(versionParts) >= 2:
        try:
            major = int(versionParts[0])
            minor = int(versionParts[1])
            if len(versionParts) > 2:
                build = int(versionParts[2])
            else:
                build = 0
        except ValueError:
            major = -1
            minor = 4
            build = -1
    else:
        major = -1
        minor = 3
        build = -1
else:
    major = -1
    minor = 2
    build = -1

buildDate = str(datetime.datetime.now())

headerFile = open(headerFilename, 'w')
headerFile.write('// FILE GENERATED BY get_git_info.py\n// DO NOT COMMIT TO REPOSITORY.\n')
headerFile.write('// CREATED: ' + buildDate + '\n\n')
headerFile.write('#define GIT_DESC   "' + desc + '"\n')
headerFile.write('#define GIT_BRANCH "' + branch + '"\n')

diffFiles = diff.splitlines();
headerFile.write('const int GIT_LOCAL_CHANGES = ' + str(len(diffFiles)) + ';\n')
headerFile.write('const char* GIT_DIFF = "')
for diffFile in diffFiles:
    headerFile.write(diffFile + '|')
headerFile.write('";\n')

headerFile.write('const int GIT_MAJOR_VERSION = ' + str(major) + ';\n')
headerFile.write('const int GIT_MINOR_VERSION = ' + str(minor) + ';\n')
headerFile.write('const int GIT_BUILD_VERSION = ' + str(build) + ';\n')
headerFile.write('const int GIT_ADDITIONAL_COMMITS = ' + str(additionalCommits) + ';\n')
headerFile.write('const char * GIT_OBJECT_NAME = "' + objectName + '";\n')
headerFile.write('const char * BUILD_DATE = "' + buildDate + '";\n')

os.chdir(old_cwd)